In [1]:
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
import pandas as pd

In [2]:
df =pd.read_csv("companies.csv")

In [3]:
df

Productivity_Exp  Management_Exp  Promotions_Exp       State     Profit
0          220349.20       236897.80       521784.10       Texas  242261.83
1          217597.70       251377.59       493898.53    Illinois  241792.06
2          208441.51       201145.55       457934.54  Washington  241050.39
3          199372.41       218671.85       433199.62       Texas  232901.99
4          197107.34       191391.77       416168.42  Washington  216187.94
5          186876.90       199814.71       412861.36       Texas  206991.12
6          189615.46       247198.87       177716.82    Illinois  206122.51
7          185298.13       245530.06       373876.68  Washington  205752.60
8          175542.52       248718.95       361613.29       Texas  202211.77
9          178334.88       208679.17       354981.62    Illinois  199759.96
10         156913.08       210594.11       279160.95  Washington  196121.95
11         155671.96       191790.61       299744.55    Illinois  194259.40
12         148863.75       227320.38       299839.44  Washington  191585.52
13         146992.39       235495.07       302664.93    Illinois  184307.35
14         174943.24       256547.42       306512.92  Washington  182602.65
15         169523.61       222616.84       311776.23       Texas  179917.04
16         133013.11       221597.55       314346.06    Illinois  176992.93
17         149657.16       245077.58       332574.31       Texas  175370.37
18         146749.16       214175.79       344919.57  Washington  174266.90
19         141419.70       253514.11        50000.00       Texas  172776.86
20         131253.86       213867.30       348664.47    Illinois  168474.03
21         133389.47       253773.43       349737.29       Texas  161313.02
22         128994.56       222782.75       353319.26  Washington  160352.25
23         122532.53       205751.03       354768.73  Washington  158733.99
24         132044.01       199281.34       190574.81       Texas  158552.04
25         119664.71       239553.16       187962.62    Illinois  157404.34
26         130328.87       244135.98       184050.07  Washington  155733.54
27         127107.60       227864.55       403183.81       Texas  155008.31
28         121051.52       282645.56       168148.20  Washington  153282.38
29         120605.48       253032.06       157138.38       Texas  151004.64
30         116994.48       215641.28       141131.24  Washington  149937.59
31         116136.38       252701.92       138218.23       Texas  147483.56
32         118408.86       229219.61        96085.25    Illinois  147427.84
33         110493.95       203057.49       264634.81  Washington  146778.92
34         101426.07       257693.92       260797.67    Illinois  146712.80
35         101014.02       185047.44       255517.64       Texas  146479.51
36          83663.76       227056.21       251126.82  Washington  140708.19
37          99069.95       151283.14       247029.42    Illinois  139949.14
38          75229.59       165947.93       235265.10       Texas  131229.06
39          93558.51       182982.09       224999.30    Illinois  131005.76
40          83754.33       218546.05       222795.67    Illinois  128239.91
41          82892.92       184710.77       214470.71  Washington  127798.83
42          78640.93       196189.63       198001.11    Illinois  121498.49
43          70505.73       227382.30        85534.17       Texas  119758.98
44          77177.74       254806.14        78334.72    Illinois  115200.33
45          56000.23       224153.04        51903.93       Texas  114926.08
46          56315.46       215816.21       347114.46  Washington   99490.75
47          55000.00       235426.92        50000.00    Illinois   92559.73
48          55542.05       151743.15        50000.00       Texas   85673.41
49          55000.00       216983.80        95173.06    Illinois   64681.40

In [4]:
x= df[["Productivity_Exp","Management_Exp","Promotions_Exp"]]


In [5]:
x

Productivity_Exp  Management_Exp  Promotions_Exp
0          220349.20       236897.80       521784.10
1          217597.70       251377.59       493898.53
2          208441.51       201145.55       457934.54
3          199372.41       218671.85       433199.62
4          197107.34       191391.77       416168.42
5          186876.90       199814.71       412861.36
6          189615.46       247198.87       177716.82
7          185298.13       245530.06       373876.68
8          175542.52       248718.95       361613.29
9          178334.88       208679.17       354981.62
10         156913.08       210594.11       279160.95
11         155671.96       191790.61       299744.55
12         148863.75       227320.38       299839.44
13         146992.39       235495.07       302664.93
14         174943.24       256547.42       306512.92
15         169523.61       222616.84       311776.23
16         133013.11       221597.55       314346.06
17         149657.16       245077.58       332574.31
18         146749.16       214175.79       344919.57
19         141419.70       253514.11        50000.00
20         131253.86       213867.30       348664.47
21         133389.47       253773.43       349737.29
22         128994.56       222782.75       353319.26
23         122532.53       205751.03       354768.73
24         132044.01       199281.34       190574.81
25         119664.71       239553.16       187962.62
26         130328.87       244135.98       184050.07
27         127107.60       227864.55       403183.81
28         121051.52       282645.56       168148.20
29         120605.48       253032.06       157138.38
30         116994.48       215641.28       141131.24
31         116136.38       252701.92       138218.23
32         118408.86       229219.61        96085.25
33         110493.95       203057.49       264634.81
34         101426.07       257693.92       260797.67
35         101014.02       185047.44       255517.64
36          83663.76       227056.21       251126.82
37          99069.95       151283.14       247029.42
38          75229.59       165947.93       235265.10
39          93558.51       182982.09       224999.30
40          83754.33       218546.05       222795.67
41          82892.92       184710.77       214470.71
42          78640.93       196189.63       198001.11
43          70505.73       227382.30        85534.17
44          77177.74       254806.14        78334.72
45          56000.23       224153.04        51903.93
46          56315.46       215816.21       347114.46
47          55000.00       235426.92        50000.00
48          55542.05       151743.15        50000.00
49          55000.00       216983.80        95173.06

In [6]:
y = df[["Profit"]]

In [7]:
y

Profit
0   242261.83
1   241792.06
2   241050.39
3   232901.99
4   216187.94
5   206991.12
6   206122.51
7   205752.60
8   202211.77
9   199759.96
10  196121.95
11  194259.40
12  191585.52
13  184307.35
14  182602.65
15  179917.04
16  176992.93
17  175370.37
18  174266.90
19  172776.86
20  168474.03
21  161313.02
22  160352.25
23  158733.99
24  158552.04
25  157404.34
26  155733.54
27  155008.31
28  153282.38
29  151004.64
30  149937.59
31  147483.56
32  147427.84
33  146778.92
34  146712.80
35  146479.51
36  140708.19
37  139949.14
38  131229.06
39  131005.76
40  128239.91
41  127798.83
42  121498.49
43  119758.98
44  115200.33
45  114926.08
46   99490.75
47   92559.73
48   85673.41
49   64681.40

In [9]:
from sklearn.model_selection import train_test_split
x_train ,x_test , y_train ,y_test =train_test_split(x,y,test_size = 0.2 , random_state =True)

In [10]:
x_train

Productivity_Exp  Management_Exp  Promotions_Exp
32         118408.86       229219.61        96085.25
39          93558.51       182982.09       224999.30
21         133389.47       253773.43       349737.29
36          83663.76       227056.21       251126.82
19         141419.70       253514.11        50000.00
42          78640.93       196189.63       198001.11
49          55000.00       216983.80        95173.06
26         130328.87       244135.98       184050.07
22         128994.56       222782.75       353319.26
13         146992.39       235495.07       302664.93
41          82892.92       184710.77       214470.71
17         149657.16       245077.58       332574.31
45          56000.23       224153.04        51903.93
24         132044.01       199281.34       190574.81
23         122532.53       205751.03       354768.73
4          197107.34       191391.77       416168.42
33         110493.95       203057.49       264634.81
14         174943.24       256547.42       306512.92
30         116994.48       215641.28       141131.24
10         156913.08       210594.11       279160.95
28         121051.52       282645.56       168148.20
44          77177.74       254806.14        78334.72
34         101426.07       257693.92       260797.67
18         146749.16       214175.79       344919.57
20         131253.86       213867.30       348664.47
25         119664.71       239553.16       187962.62
6          189615.46       247198.87       177716.82
7          185298.13       245530.06       373876.68
47          55000.00       235426.92        50000.00
1          217597.70       251377.59       493898.53
16         133013.11       221597.55       314346.06
0          220349.20       236897.80       521784.10
15         169523.61       222616.84       311776.23
5          186876.90       199814.71       412861.36
11         155671.96       191790.61       299744.55
9          178334.88       208679.17       354981.62
8          175542.52       248718.95       361613.29
12         148863.75       227320.38       299839.44
43          70505.73       227382.30        85534.17
37          99069.95       151283.14       247029.42

In [11]:
y_train

Profit
32  147427.84
39  131005.76
21  161313.02
36  140708.19
19  172776.86
42  121498.49
49   64681.40
26  155733.54
22  160352.25
13  184307.35
41  127798.83
17  175370.37
45  114926.08
24  158552.04
23  158733.99
4   216187.94
33  146778.92
14  182602.65
30  149937.59
10  196121.95
28  153282.38
44  115200.33
34  146712.80
18  174266.90
20  168474.03
25  157404.34
6   206122.51
7   205752.60
47   92559.73
1   241792.06
16  176992.93
0   242261.83
15  179917.04
5   206991.12
11  194259.40
9   199759.96
8   202211.77
12  191585.52
43  119758.98
37  139949.14

In [13]:
from sklearn.linear_model import LinearRegression
model1=LinearRegression()

In [14]:
model1


LinearRegression()

In [15]:
model1.fit(x_train,y_train)

LinearRegression()

In [16]:
model1.intercept_


array([56487.74917417])

In [17]:
model1.coef_

array([[ 0.7742023 , -0.00877164,  0.02934891]])

In [18]:
model1.predict([[99069.95,151283.14,247029.42]])

C:\Users\prana\OneDrive\Desktop\python setup\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[139110.9770016]])

In [19]:
y_pred = model1.predict(x_test)
y_pred

array([[164729.00768236],
       [140569.03231312],
       [125952.34861633],
       [120179.81117586],
       [229539.15187896],
       [221638.15637459],
       [ 99624.94193162],
       [152253.12475568],
       [108381.67907   ],
       [148240.74724733]])

In [21]:
from sklearn.metrics import r2_score,mean_squared_error, mean_absolute_error
r2_score(y_test,y_pred)

0.9650940934427323

In [22]:
dataset = pd.DataFrame({"Prod_exp":x_test.iloc[:,0]
                        ,"Management_Exp":x_test.iloc[:,1],	"Promotions_Exp":x_test.iloc[:,2]	,"profit":y_test.squeeze(),"Predicted profit":y_pred.squeeze(),"Difference":(y_test-y_pred).squeeze()})
dataset

Prod_exp  Management_Exp  Promotions_Exp     profit  Predicted profit  \
27  127107.60       227864.55       403183.81  155008.31     164729.007682   
35  101014.02       185047.44       255517.64  146479.51     140569.032313   
40   83754.33       218546.05       222795.67  128239.91     125952.348616   
38   75229.59       165947.93       235265.10  131229.06     120179.811176   
2   208441.51       201145.55       457934.54  241050.39     229539.151879   
3   199372.41       218671.85       433199.62  232901.99     221638.156375   
48   55542.05       151743.15        50000.00   85673.41      99624.941932   
29  120605.48       253032.06       157138.38  151004.64     152253.124756   
46   56315.46       215816.21       347114.46   99490.75     108381.679070   
31  116136.38       252701.92       138218.23  147483.56     148240.747247   

      Difference  
27  -9720.697682  
35   5910.477687  
40   2287.561384  
38  11049.248824  
2   11511.238121  
3   11263.833625  
48 -13951.531932  
29  -1248.484756  
46  -8890.929070  
31   -757.187247

In [24]:
mean_absolute_error(y_test, y_pred)

7659.119032814689

In [25]:
mean_squared_error(y_test, y_pred)

79195300.72807223